# Docs: <https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/customizing-dependency-updates>

version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule: {interval: monthly}
    reviewers: [tarampampam]
    assignees: [tarampampam]

  - package-ecosystem: docker
    directory: /
    schedule: {interval: monthly}
    reviewers: [tarampampam]
    assignees: [tarampampam]

  - package-ecosystem: npm
    directory: /frontend
    open-pull-requests-limit: 15
    schedule: {interval: monthly}
    reviewers: [tarampampam]
    assignees: [tarampampam]
