version: '3.8'

services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - '80:80/tcp'
      - '443:443/tcp'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks: [indocker-app-network]
    security_opt: [no-new-privileges:true]

  frontend:
    image: caddy:2.6-alpine
    volumes:
      - ./frontend:/usr/share/caddy:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend-router.rule=Host(`frontend.indocker.app`)
      - traefik.http.routers.frontend-router.service=frontend-service
      - traefik.http.services.frontend-service.loadbalancer.server.port=80
    networks: [indocker-app-network]
    security_opt: [no-new-privileges:true]

networks:
  indocker-app-network:
    external: true
