# Dynamic configuration

tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/fullchain1.pem
        keyFile: /etc/traefik/certs/privkey1.pem

http:
  middlewares:
    indocker-middleware: # sources are located in traefik/plugins/indocker directory
      plugin:
        indocker: {}

    traefik-dashboard-cors:
      headers:
        accessControlAllowOriginList:
          - https://indocker.app
          - https://frontend.indocker.app # for local development
        accessControlAllowMethods: [GET]

  routers:
    traefik-dashboard-router:
      rule: Host(`monitor.indocker.app`)
      entryPoints: [https]
      service: api@internal
      tls: {} # force TLS usage
      middlewares:
        - traefik-dashboard-cors # allow limited CORS for traefik dashboard API
        - indocker-middleware # use our local indocker plugin together with the traefik dashboard API
