# Dynamic configuration

tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/fullchain1.pem
        keyFile: /etc/traefik/certs/privkey1.pem

http:
  middlewares:
    local-middleware: # sources are located in traefik/plugins/middleware directory
      plugin:
        local-middleware: {} # plugin and middleware names are same

    traefik-dashboard-cors:
      headers:
        accessControlAllowOriginList:
          - https://indocker.app
          - https://frontend.indocker.app # for local development
        accessControlAllowMethods: [GET]

  routers:
    traefik-dashboard-router:
      rule: Host(`monitor.indocker.app`)
      entryPoints: [https]
      service: api@internal
      tls: {} # force TLS usage
      middlewares:
        - traefik-dashboard-cors # allow limited CORS for traefik dashboard API
        - local-middleware # use our local middleware together with the traefik dashboard API
