# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: 🚀 Deploy the site

on:
  workflow_dispatch: {}
  push:
    branches: [master, main]
    paths: [site/**, .github/workflows/deploy-site.yml]

concurrency:
  group: ${{ github.ref }}-site
  cancel-in-progress: true

jobs:
  deploy:
    name: 🖼 Deploy the site
    runs-on: ubuntu-latest
    environment:
      name: Site
      url: https://indocker.app
    steps:
      - uses: actions/checkout@v4
      - uses: cloudflare/wrangler-action@v3
        env: {PROJECT_NAME: indocker-app-index, DIST_DIR: ./site, CF_BRANCH_NAME: main}
        with:
          apiToken: ${{ secrets.CF_PAGES_DEPLOY_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command:
            pages deploy ${{ env.DIST_DIR }}
            --project-name=${{ env.PROJECT_NAME }}
            --branch ${{ env.CF_BRANCH_NAME }}
            --commit-dirty=true
