# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: 🚀 Release

on:
  release: {types: [published]}
  workflow_dispatch: {}

jobs:
  build-docker-image:
    name: 🏗️ Build the docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_LOGIN }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - {uses: gacts/github-slug@v1, id: slug}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm/v6,linux/arm64/v8
          build-args: "APP_VERSION=${{ steps.slug.outputs.version }}"
          # TODO: add `ghcr.io/tarampampam/indocker:latest` and `quay.io/indocker/app:latest`
          tags: |
            ghcr.io/tarampampam/indocker:${{ steps.slug.outputs.version-major }}.${{ steps.slug.outputs.version-minor }}.${{ steps.slug.outputs.version-patch }}
            ghcr.io/tarampampam/indocker:${{ steps.slug.outputs.version-major }}.${{ steps.slug.outputs.version-minor }}
            ghcr.io/tarampampam/indocker:${{ steps.slug.outputs.version-major }}
            quay.io/indocker/app:${{ steps.slug.outputs.version-major }}.${{ steps.slug.outputs.version-minor }}.${{ steps.slug.outputs.version-patch }}
            quay.io/indocker/app:${{ steps.slug.outputs.version-major }}.${{ steps.slug.outputs.version-minor }}
            quay.io/indocker/app:${{ steps.slug.outputs.version-major }}
